#!/usr/bin/env bash

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config external_bar all:30:0 \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_zoom_persist off \
  window_placement second_child \
  window_topmost off \
  window_shadow float \
  window_opacity on \
  window_opacity_duration 0.15 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.95 \
  window_border_width 2 \
  window_border_hidpi off \
  window_border_radius 11 \
  window_animation_duration 0.22 \
  active_window_border_color 0xffe1e3e4 \
  normal_window_border_color 0xff2a2f38 \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  auto_balance off \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  \
  top_padding 10 \
  bottom_padding 10 \
  left_padding 10 \
  right_padding 10 \
  window_gap 10

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^Okta Verify$" manage=off
yabai -m rule --add app="^vault_token_generator_v2_mac$" manage=off
yabai -m rule --add app="^Unclutter$" manage=off
yabai -m rule --add app="^Sublime Merge$" manage=off
yabai -m rule --add app="^DevToys$" manage=off

# yabai -m rule --add app="^Things$" manage=off
yabai -m config layout bsp

echo "yabai configuration loaded.."
