#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: sync-mcporter-instructions [options]

Generate Pi mcporter instruction markdown from currently available mcporter MCP tools.

Options:
  --config PATH      mcporter config path (default: ~/.mcporter/mcporter.json if present)
  --profile NAME     profile: work or personal (default: work). Selects default output file.
  --output PATH      output path (default: .../pi/instructions/mcporter.<profile>.md)
  --max-tools N      max selectors to include (default: 40)
  --timeout MS       mcporter list timeout in ms (default: 30000)
  --check            fail if output file is stale; do not write
  --allow-empty      allow writing file when no tools are available
  -h, --help         show this help
EOF
}

config_path="${MCPORTER_CONFIG:-}"
output_path="${MCPORTER_INSTRUCTIONS_OUTPUT:-}"
profile="${MCPORTER_PROFILE:-work}"
max_tools="${MCPORTER_MAX_TOOLS:-40}"
timeout_ms="${MCPORTER_TIMEOUT:-30000}"
check_mode=0
allow_empty=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      [[ $# -ge 2 ]] || { echo "error: --config requires PATH" >&2; exit 2; }
      config_path="$2"
      shift 2
      ;;
    --profile)
      [[ $# -ge 2 ]] || { echo "error: --profile requires NAME" >&2; exit 2; }
      profile="$2"
      shift 2
      ;;
    --output)
      [[ $# -ge 2 ]] || { echo "error: --output requires PATH" >&2; exit 2; }
      output_path="$2"
      shift 2
      ;;
    --max-tools)
      [[ $# -ge 2 ]] || { echo "error: --max-tools requires N" >&2; exit 2; }
      max_tools="$2"
      shift 2
      ;;
    --timeout)
      [[ $# -ge 2 ]] || { echo "error: --timeout requires MS" >&2; exit 2; }
      timeout_ms="$2"
      shift 2
      ;;
    --check)
      check_mode=1
      shift
      ;;
    --allow-empty)
      allow_empty=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

[[ "$max_tools" =~ ^[0-9]+$ ]] || { echo "error: --max-tools must be a non-negative integer" >&2; exit 2; }
[[ "$timeout_ms" =~ ^[0-9]+$ ]] || { echo "error: --timeout must be a non-negative integer" >&2; exit 2; }
[[ "$profile" == "work" || "$profile" == "personal" ]] || { echo "error: --profile must be work or personal" >&2; exit 2; }
if [[ -z "$output_path" ]]; then
  output_path="modules/home-manager/features/ai-tools/pi/instructions/mcporter.${profile}.md"
fi

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
expected_dir="$repo_root/modules/home-manager/features/ai-tools/pi/instructions"
if [[ ! -d "$expected_dir" ]]; then
  echo "error: expected repo layout not found: $expected_dir" >&2
  exit 1
fi

if [[ "$output_path" != /* ]]; then
  output_path="$repo_root/$output_path"
fi

if [[ -z "$config_path" && -r "$HOME/.mcporter/mcporter.json" ]]; then
  config_path="$HOME/.mcporter/mcporter.json"
fi

if [[ -n "$config_path" && ! -r "$config_path" ]]; then
  echo "error: mcporter config not readable: $config_path" >&2
  exit 1
fi

tmp_json="$(mktemp)"
tmp_out="$(mktemp)"
trap 'rm -f "$tmp_json" "$tmp_out" "$tmp_write"' EXIT
tmp_write=""

mcporter_cmd=(mcporter)
if [[ -n "$config_path" ]]; then
  mcporter_cmd+=(--config "$config_path")
fi
mcporter_cmd+=(list --json --timeout "$timeout_ms")

if ! NO_COLOR=1 CI=1 MCPORTER_NO_SPINNER=1 "${mcporter_cmd[@]}" >"$tmp_json"; then
  echo "error: mcporter list failed; output file left unchanged" >&2
  exit 1
fi

if ! jq -e '.mode == "list" and (.servers | type == "array")' "$tmp_json" >/dev/null; then
  echo "error: unexpected mcporter JSON shape; output file left unchanged" >&2
  exit 1
fi

tool_count="$(jq '[.servers[]? | select(.status == "ok") | .name as $server | (.tools // [])[]? | {selector: ($server + "." + .name)}] | unique_by(.selector) | length' "$tmp_json")"
if [[ "$tool_count" -eq 0 && "$allow_empty" -ne 1 ]]; then
  echo "error: no available MCP tools found; output file left unchanged (use --allow-empty to override)" >&2
  exit 1
fi

jq -r --argjson maxTools "$max_tools" '
  def oneline:
    tostring
    | gsub("[\\r\\n\\t ]+"; " ")
    | gsub("^ +| +$"; "");
  def clip($n):
    if length > $n then .[0:($n - 1)] + "…" else . end;
  def tools:
    [.servers[]?
      | select(.status == "ok")
      | .name as $server
      | (.tools // [])[]?
      | {
          selector: ($server + "." + .name),
          description: ((.description // "No description.") | oneline | sub("\\. .*$"; ".") | clip(200))
        }
    ]
    | unique_by(.selector)
    | sort_by(.selector);
  def skipped:
    [.servers[]?
      | select(.status != "ok")
      | {
          name,
          status,
          issue: ((.issue.rawMessage // .error // "unavailable") | oneline | clip(140))
        }
    ]
    | sort_by(.name);

  (tools) as $tools |
  (skipped) as $skipped |
  ($tools | length) as $total |
  [
    "<!-- Generated by nix run .#sync-mcporter-instructions. Do not edit by hand. -->",
    "",
    "# MCPorter Tool Catalog",
    "",
    "MCPorter discovered these MCP tools from the current local mcporter configuration.",
    "",
    "When one of these selectors clearly matches the user request, call `mcporter` with `action=\"call\"` directly. Use `action=\"describe\"` for schema details. Use `action=\"search\"` only when no warmed selector fits.",
    "",
    "## Warmed MCP selectors",
    "",
    (if $total == 0 then
      "_No available MCP tools found._"
    else
      ($tools[0:$maxTools][] | "- `\(.selector)` — \(.description)")
    end),
    (if $total > $maxTools then
      "- … \($total - $maxTools) more tools omitted by --max-tools=\($maxTools). Run `nix run .#sync-mcporter-instructions -- --max-tools \($total)` to include all."
    else empty end),
    (if ($skipped | length) > 0 then
      "",
      "## Skipped MCP servers",
      "",
      ($skipped[] | "- `\(.name)` — \(.status): \(.issue)")
    else empty end),
    ""
  ] | .[]
' "$tmp_json" >"$tmp_out"

if [[ "$check_mode" -eq 1 ]]; then
  if [[ ! -f "$output_path" ]]; then
    echo "error: output file missing: $output_path" >&2
    exit 1
  fi
  if ! cmp -s "$tmp_out" "$output_path"; then
    echo "error: mcporter instructions are stale: $output_path" >&2
    diff -u "$output_path" "$tmp_out" || true
    exit 1
  fi
  echo "mcporter instructions up to date: $output_path ($tool_count tools available)"
  exit 0
fi

mkdir -p "$(dirname "$output_path")"
tmp_write="$(mktemp "$(dirname "$output_path")/.mcporter.md.tmp.XXXXXX")"
cp "$tmp_out" "$tmp_write"
mv "$tmp_write" "$output_path"
tmp_write=""

echo "wrote $output_path ($tool_count tools available; max $max_tools included)"
