nix flake update nixpkgs
nix flake update nixpkgs-stable
nix flake update nixos-hardware
nix flake update home-manager
nix flake update disko
nix flake update nix-gaming
nix flake update nix-flatpak
nix flake update xremap-flake
nix flake update fw-fanctrl
